port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
....................
proxy-groups:
  - name: 🚀 手动选择
    type: select
    proxies:
....................
  - name: ♻️ 自动选择
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 150
    tolerance: 60
    proxies:
....................
  - name: 💬 即时通讯
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🌐 社交媒体
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🚀 GitHub
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🤖 ChatGPT
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🤖 Copilot
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🤖 AI服务
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🎶 TikTok
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 📹 YouTube
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🎥 Netflix
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🎥 DisneyPlus
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🎥 HBO
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🎥 PrimeVideo
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🎥 AppleTV+
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🎥 Emby
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🎻 Spotify
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 📺 Bahamut
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🌎 国外媒体
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🛒 国外电商
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 📢 谷歌FCM
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🇬 谷歌服务
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 手动选择
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 手动选择
  - name: 🎮 游戏平台
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 手动选择
  - name: 🎮 Steam
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 手动选择
  - name: 🚀 测速工具
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 手动选择
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🔀 非标端口
    type: select
    proxies:
      - 🐟 遵循规则
      - 🎯 全球直连
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
  - name: 🐟 遵循规则
    type: select
    proxies:
      - 🐟 漏网之鱼
rules:
  - IP-CIDR,192.168.1.10/32,🎯 全球直连
  - IP-CIDR,172.10.0.0/24,🎯 全球直连
  - GEOSITE,private,🎯 全球直连
  - GEOIP,private,🎯 全球直连,no-resolve
  - DOMAIN-KEYWORD,m-team,🎯 全球直连
  - DOMAIN-KEYWORD,quickconnect,🎯 全球直连
  - DOMAIN-KEYWORD,synology,🎯 全球直连
  - DOMAIN-SUFFIX,03241119.xyz,🎯 全球直连
  - DOMAIN-SUFFIX,112114.xyz,🎯 全球直连
  - DOMAIN-SUFFIX,115cdn.de,🎯 全球直连
  - DOMAIN-SUFFIX,1996999.xyz,🎯 全球直连
  - DOMAIN-SUFFIX,204cloud.com,🎯 全球直连
  - DOMAIN-SUFFIX,4399zmxy.com,🎯 全球直连
  - DOMAIN-SUFFIX,51wanxue.com,🎯 全球直连
  - DOMAIN-SUFFIX,51zmt.top,🎯 全球直连
  - DOMAIN-SUFFIX,52jiawei.com,🎯 全球直连
  - DOMAIN-SUFFIX,52met.com,🎯 全球直连
  - DOMAIN-SUFFIX,52muban.com,🎯 全球直连
  - DOMAIN-SUFFIX,55555.ink,🎯 全球直连
  - DOMAIN-SUFFIX,657192.com,🎯 全球直连
  - DOMAIN-SUFFIX,6v520.net,🎯 全球直连
  - DOMAIN-SUFFIX,737698.xyz,🎯 全球直连
  - DOMAIN-SUFFIX,7sef.com,🎯 全球直连
  - DOMAIN-SUFFIX,86656.net,🎯 全球直连
  - DOMAIN-SUFFIX,900cha.com,🎯 全球直连
  - DOMAIN-SUFFIX,985hezi.com,🎯 全球直连
  - DOMAIN-SUFFIX,998tool.com,🎯 全球直连
  - DOMAIN-SUFFIX,adobe.com,🎯 全球直连
  - DOMAIN-SUFFIX,afeica.com,🎯 全球直连
  - DOMAIN-SUFFIX,afuns.me,🎯 全球直连
  - DOMAIN-SUFFIX,aistudio-app.com,🎯 全球直连
  - DOMAIN-SUFFIX,akamaihd.net,🎯 全球直连
  - DOMAIN-SUFFIX,akamaized.net,🎯 全球直连
  - DOMAIN-SUFFIX,aloys233.top,🎯 全球直连
  - DOMAIN-SUFFIX,anycubic.com,🎯 全球直连
  - DOMAIN-SUFFIX,api.myip.com,🎯 全球直连
  - DOMAIN-SUFFIX,armvm.com,🎯 全球直连
  - DOMAIN-SUFFIX,baiyishequ.com,🎯 全球直连
  - DOMAIN-SUFFIX,bangumi.tv,🎯 全球直连
  - DOMAIN-SUFFIX,bdcb.cc,🎯 全球直连
  - DOMAIN-SUFFIX,belimked.com,🎯 全球直连
  - DOMAIN-SUFFIX,bgm.tv,🎯 全球直连
  - DOMAIN-SUFFIX,bochk.com,🎯 全球直连
  - DOMAIN-SUFFIX,boyuemobile.com,🎯 全球直连
  - DOMAIN-SUFFIX,bsbsb.top,🎯 全球直连
  - DOMAIN-SUFFIX,canghaiip.com,🎯 全球直连
  - DOMAIN-SUFFIX,cdn.ist,🎯 全球直连
  - DOMAIN-SUFFIX,centbrowser.net,🎯 全球直连
  - DOMAIN-SUFFIX,cg3da.com,🎯 全球直连
  - DOMAIN-SUFFIX,chaxunjiao.com,🎯 全球直连
  - DOMAIN-SUFFIX,chaz.fun,🎯 全球直连
  - DOMAIN-SUFFIX,checkip.dyndns.org,🎯 全球直连
  - DOMAIN-SUFFIX,checkipv6.dyndns.org,🎯 全球直连
  - DOMAIN-SUFFIX,chenyuxia.com,🎯 全球直连
  - DOMAIN-SUFFIX,chii.in,🎯 全球直连
  - DOMAIN-SUFFIX,chujingapp.com,🎯 全球直连
  - DOMAIN-SUFFIX,clivia.fun,🎯 全球直连
  - DOMAIN-SUFFIX,cn-music.mefun.vip,🎯 全球直连
  - DOMAIN-SUFFIX,cnb.space,🎯 全球直连
  - DOMAIN-SUFFIX,codeloop.top,🎯 全球直连
  - DOMAIN-SUFFIX,congmiqq.com,🎯 全球直连
  - DOMAIN-SUFFIX,coros.com,🎯 全球直连
  - DOMAIN-SUFFIX,crtyhr.com,🎯 全球直连
  - DOMAIN-SUFFIX,dcgstd.com,🎯 全球直连
  - DOMAIN-SUFFIX,ddsrem.com,🎯 全球直连
  - DOMAIN-SUFFIX,ddzn.tech,🎯 全球直连
  - DOMAIN-SUFFIX,dell.com,🎯 全球直连
  - DOMAIN-SUFFIX,dhub.kubesre.xyz,🎯 全球直连
  - DOMAIN-SUFFIX,dingdingzn.com,🎯 全球直连
  - DOMAIN-SUFFIX,diyiedu.com,🎯 全球直连
  - DOMAIN-SUFFIX,docker.1panel.live,🎯 全球直连
  - DOMAIN-SUFFIX,docker.kejilion.pro,🎯 全球直连
  - DOMAIN-SUFFIX,docker.unsee.tech,🎯 全球直连
  - DOMAIN-SUFFIX,dockerpull.org,🎯 全球直连
  - DOMAIN-SUFFIX,dockerpull.pw,🎯 全球直连
  - DOMAIN-SUFFIX,dothantech.com,🎯 全球直连
  - DOMAIN-SUFFIX,douqq.com,🎯 全球直连
  - DOMAIN-SUFFIX,dushe1.app,🎯 全球直连
  - DOMAIN-SUFFIX,einfo-tech.com,🎯 全球直连
  - DOMAIN-SUFFIX,englibrary.com,🎯 全球直连
  - DOMAIN-SUFFIX,epg.aptv.app,🎯 全球直连
  - DOMAIN-SUFFIX,epg.v1.mk,🎯 全球直连
  - DOMAIN-SUFFIX,everdrawing.com,🎯 全球直连
  - DOMAIN-SUFFIX,feihengip.com,🎯 全球直连
  - DOMAIN-SUFFIX,feizhiyi.com,🎯 全球直连
  - DOMAIN-SUFFIX,fengsutb.com,🎯 全球直连
  - DOMAIN-SUFFIX,ffhome.com,🎯 全球直连
  - DOMAIN-SUFFIX,fjpit.com,🎯 全球直连
  - DOMAIN-SUFFIX,flingtrainer.com,🎯 全球直连
  - DOMAIN-SUFFIX,fofuai.com,🎯 全球直连
  - DOMAIN-SUFFIX,fowep.com,🎯 全球直连
  - DOMAIN-SUFFIX,freetv.top,🎯 全球直连
  - DOMAIN-SUFFIX,frp-ski.com,🎯 全球直连
  - DOMAIN-SUFFIX,fssbcc.top,🎯 全球直连
  - DOMAIN-SUFFIX,fsytss.com,🎯 全球直连
  - DOMAIN-SUFFIX,ft07.com,🎯 全球直连
  - DOMAIN-SUFFIX,fzvcolco.com,🎯 全球直连
  - DOMAIN-SUFFIX,fzwqq.com,🎯 全球直连
  - DOMAIN-SUFFIX,gaishitongshu.com,🎯 全球直连
  - DOMAIN-SUFFIX,game.maj-soul.com,🎯 全球直连
  - DOMAIN-SUFFIX,gangtise.com,🎯 全球直连
  - DOMAIN-SUFFIX,gaojiua.com,🎯 全球直连
  - DOMAIN-SUFFIX,gdcucc.v1.mk,🎯 全球直连
  - DOMAIN-SUFFIX,geektool.top,🎯 全球直连
  - DOMAIN-SUFFIX,ggbond.org,🎯 全球直连
  - DOMAIN-SUFFIX,gh-proxy.com,🎯 全球直连
  - DOMAIN-SUFFIX,gh.con.sh,🎯 全球直连
  - DOMAIN-SUFFIX,gh.ddlc.top,🎯 全球直连
  - DOMAIN-SUFFIX,gh.llkk.cc,🎯 全球直连
  - DOMAIN-SUFFIX,ghfast.top,🎯 全球直连
  - DOMAIN-SUFFIX,ghp.ci,🎯 全球直连
  - DOMAIN-SUFFIX,ghproxy.cc,🎯 全球直连
  - DOMAIN-SUFFIX,ghproxy.cfd,🎯 全球直连
  - DOMAIN-SUFFIX,ghps.cc,🎯 全球直连
  - DOMAIN-SUFFIX,girigirilove.com,🎯 全球直连
  - DOMAIN-SUFFIX,git.886.be,🎯 全球直连
  - DOMAIN-SUFFIX,github.abskoop.workers.dev,🎯 全球直连
  - DOMAIN-SUFFIX,github.boki.moe,🎯 全球直连
  - DOMAIN-SUFFIX,github.moeyy.xyz,🎯 全球直连
  - DOMAIN-SUFFIX,github.site,🎯 全球直连
  - DOMAIN-SUFFIX,github.store,🎯 全球直连
  - DOMAIN-SUFFIX,giveup.top,🎯 全球直连
  - DOMAIN-SUFFIX,gjtool.com,🎯 全球直连
  - DOMAIN-SUFFIX,gmoj.net,🎯 全球直连
  - DOMAIN-SUFFIX,gmya.net,🎯 全球直连
  - DOMAIN-SUFFIX,goalmapapp.com,🎯 全球直连
  - DOMAIN-SUFFIX,goka.top,🎯 全球直连
  - DOMAIN-SUFFIX,googoc.com,🎯 全球直连
  - DOMAIN-SUFFIX,gootho.com,🎯 全球直连
  - DOMAIN-SUFFIX,gseen.com,🎯 全球直连
  - DOMAIN-SUFFIX,gsgltz.com,🎯 全球直连
  - DOMAIN-SUFFIX,gsjkjt.com,🎯 全球直连
  - DOMAIN-SUFFIX,gsnhcg.com,🎯 全球直连
  - DOMAIN-SUFFIX,gsstic.com,🎯 全球直连
  - DOMAIN-SUFFIX,gxnnjidingkeji.top,🎯 全球直连
  - DOMAIN-SUFFIX,gzybao.com,🎯 全球直连
  - DOMAIN-SUFFIX,halvie.com,🎯 全球直连
  - DOMAIN-SUFFIX,haoxueche.com,🎯 全球直连
  - DOMAIN-SUFFIX,hbcof.com,🎯 全球直连
  - DOMAIN-SUFFIX,hbctic.com,🎯 全球直连
  - DOMAIN-SUFFIX,hexiny.com,🎯 全球直连
  - DOMAIN-SUFFIX,hf-mirror.com,🎯 全球直连
  - DOMAIN-SUFFIX,hnxzctec.com,🎯 全球直连
  - DOMAIN-SUFFIX,hsbc.com.hk,🎯 全球直连
  - DOMAIN-SUFFIX,hstbroker.com,🎯 全球直连
  - DOMAIN-SUFFIX,hszq6.com,🎯 全球直连
  - DOMAIN-SUFFIX,hub.crdz.gq,🎯 全球直连
  - DOMAIN-SUFFIX,hub.gitmirror.com,🎯 全球直连
  - DOMAIN-SUFFIX,hub.rat.dev,🎯 全球直连
  - DOMAIN-SUFFIX,hub.xdark.top,🎯 全球直连
  - DOMAIN-SUFFIX,huikao8.com,🎯 全球直连
  - DOMAIN-SUFFIX,hwbim.com,🎯 全球直连
  - DOMAIN-SUFFIX,hwjianmo.com,🎯 全球直连
  - DOMAIN-SUFFIX,hwzuku.com,🎯 全球直连
  - DOMAIN-SUFFIX,hzlawyer.net,🎯 全球直连
  - DOMAIN-SUFFIX,icvcs.com,🎯 全球直连
  - DOMAIN-SUFFIX,idsduf.com,🎯 全球直连
  - DOMAIN-SUFFIX,ifconfig.co,🎯 全球直连
  - DOMAIN-SUFFIX,ifengmap.com,🎯 全球直连
  - DOMAIN-SUFFIX,ifish7.com,🎯 全球直连
  - DOMAIN-SUFFIX,igpsport.com,🎯 全球直连
  - DOMAIN-SUFFIX,imacos.top,🎯 全球直连
  - DOMAIN-SUFFIX,immortalwrt.org,🎯 全球直连
  - DOMAIN-SUFFIX,iotrix.net,🎯 全球直连
  - DOMAIN-SUFFIX,ip159.com,🎯 全球直连
  - DOMAIN-SUFFIX,ip6.seeip.org,🎯 全球直连
  - DOMAIN-SUFFIX,ipapi.co,🎯 全球直连
  - DOMAIN-SUFFIX,ipinfo.io,🎯 全球直连
  - DOMAIN-SUFFIX,ipshu.com,🎯 全球直连
  - DOMAIN-SUFFIX,istoreos.com,🎯 全球直连
  - DOMAIN-SUFFIX,jsdelivr.net,🎯 全球直连
  - DOMAIN-SUFFIX,julebu.co,🎯 全球直连
  - DOMAIN-SUFFIX,jxjktzjt.com,🎯 全球直连
  - DOMAIN-SUFFIX,jxpp.com,🎯 全球直连
  - DOMAIN-SUFFIX,kaspersky-labs.com,🎯 全球直连
  - DOMAIN-SUFFIX,kaspersky.com,🎯 全球直连
  - DOMAIN-SUFFIX,keyoo.com,🎯 全球直连
  - DOMAIN-SUFFIX,kgithub.com,🎯 全球直连
  - DOMAIN-SUFFIX,kit327.com,🎯 全球直连
  - DOMAIN-SUFFIX,kmeila.com,🎯 全球直连
  - DOMAIN-SUFFIX,kuaicha888.com,🎯 全球直连
  - DOMAIN-SUFFIX,kyarucloud.moe,🎯 全球直连
  - DOMAIN-SUFFIX,lanyun.net,🎯 全球直连
  - DOMAIN-SUFFIX,leelen.com,🎯 全球直连
  - DOMAIN-SUFFIX,letaoedu.com,🎯 全球直连
  - DOMAIN-SUFFIX,liunn.com,🎯 全球直连
  - DOMAIN-SUFFIX,longmenshuju.com,🎯 全球直连
  - DOMAIN-SUFFIX,lsbj365.com,🎯 全球直连
  - DOMAIN-SUFFIX,lyihub.com,🎯 全球直连
  - DOMAIN-SUFFIX,lyilife.com,🎯 全球直连
  - DOMAIN-SUFFIX,m-team.cc,🎯 全球直连
  - DOMAIN-SUFFIX,m-team.io,🎯 全球直连
  - DOMAIN-SUFFIX,manfuz.co,🎯 全球直连
  - DOMAIN-SUFFIX,mc-user.com,🎯 全球直连
  - DOMAIN-SUFFIX,meishiffx.online,🎯 全球直连
  - DOMAIN-SUFFIX,members.3322.org,🎯 全球直连
  - DOMAIN-SUFFIX,micu.hk,🎯 全球直连
  - DOMAIN-SUFFIX,mifeng.plus,🎯 全球直连
  - DOMAIN-SUFFIX,mobai.sbs,🎯 全球直连
  - DOMAIN-SUFFIX,modelscope.net,🎯 全球直连
  - DOMAIN-SUFFIX,msftconnecttest.com,🎯 全球直连
  - DOMAIN-SUFFIX,msftncsi.com,🎯 全球直连
  - DOMAIN-SUFFIX,mslmc.net,🎯 全球直连
  - DOMAIN-SUFFIX,mtaokj.com,🎯 全球直连
  - DOMAIN-SUFFIX,mykuaidi.com,🎯 全球直连
  - DOMAIN-SUFFIX,myshopex.com,🎯 全球直连
  - DOMAIN-SUFFIX,naixi.com,🎯 全球直连
  - DOMAIN-SUFFIX,neihang.net,🎯 全球直连
  - DOMAIN-SUFFIX,netzz.net,🎯 全球直连
  - DOMAIN-SUFFIX,nhk.or.jp,🎯 全球直连
  - DOMAIN-SUFFIX,nn.ci,🎯 全球直连
  - DOMAIN-SUFFIX,nxog.top,🎯 全球直连
  - DOMAIN-SUFFIX,oceando.cloud,🎯 全球直连
  - DOMAIN-SUFFIX,ok321.top,🎯 全球直连
  - DOMAIN-SUFFIX,onebuygz.com,🎯 全球直连
  - DOMAIN-SUFFIX,ottai.com,🎯 全球直连
  - DOMAIN-SUFFIX,ourschool.cc,🎯 全球直连
  - DOMAIN-SUFFIX,paperang.com,🎯 全球直连
  - DOMAIN-SUFFIX,plusde1.younoyes.com,🎯 全球直连
  - DOMAIN-SUFFIX,plushk1.younoyes.com,🎯 全球直连
  - DOMAIN-SUFFIX,plushk2.younoyes.com,🎯 全球直连
  - DOMAIN-SUFFIX,plushk3.younoyes.com,🎯 全球直连
  - DOMAIN-SUFFIX,plusjp1.younoyes.com,🎯 全球直连
  - DOMAIN-SUFFIX,plusus1.younoyes.com,🎯 全球直连
  - DOMAIN-SUFFIX,plusus2.younoyes.com,🎯 全球直连
  - DOMAIN-SUFFIX,plusus3.younoyes.com,🎯 全球直连
  - DOMAIN-SUFFIX,pool.ntp.org,🎯 全球直连
  - DOMAIN-SUFFIX,powershellgallery.com,🎯 全球直连
  - DOMAIN-SUFFIX,privateapi.xyz,🎯 全球直连
  - DOMAIN-SUFFIX,ptl.gs,🎯 全球直连
  - DOMAIN-SUFFIX,ptlgs.org,🎯 全球直连
  - DOMAIN-SUFFIX,qiankunshopping.com,🎯 全球直连
  - DOMAIN-SUFFIX,qianuni.com,🎯 全球直连
  - DOMAIN-SUFFIX,qianxuecloud.com,🎯 全球直连
  - DOMAIN-SUFFIX,qianxueyunke.com,🎯 全球直连
  - DOMAIN-SUFFIX,qiaoxuesi.com,🎯 全球直连
  - DOMAIN-SUFFIX,qinglue.com,🎯 全球直连
  - DOMAIN-SUFFIX,redenmc.com,🎯 全球直连
  - DOMAIN-SUFFIX,registry.dockermirror.com,🎯 全球直连
  - DOMAIN-SUFFIX,rewards.bing.com,🎯 全球直连
  - DOMAIN-SUFFIX,rsfcxq.com,🎯 全球直连
  - DOMAIN-SUFFIX,saduck.top,🎯 全球直连
  - DOMAIN-SUFFIX,sanligu.top,🎯 全球直连
  - DOMAIN-SUFFIX,sapphiretech.com,🎯 全球直连
  - DOMAIN-SUFFIX,scbaijia.com,🎯 全球直连
  - DOMAIN-SUFFIX,seaflysoft.com,🎯 全球直连
  - DOMAIN-SUFFIX,seedpace.com,🎯 全球直连
  - DOMAIN-SUFFIX,sgtv.ii00.cc,🎯 全球直连
  - DOMAIN-SUFFIX,shineacc.com,🎯 全球直连
  - DOMAIN-SUFFIX,shuqiandiqiu.com,🎯 全球直连
  - DOMAIN-SUFFIX,sixloy428.top,🎯 全球直连
  - DOMAIN-SUFFIX,sksight.com,🎯 全球直连
  - DOMAIN-SUFFIX,snfox.com,🎯 全球直连
  - DOMAIN-SUFFIX,snltty.com,🎯 全球直连
  - DOMAIN-SUFFIX,sptv.ii00.cc,🎯 全球直连
  - DOMAIN-SUFFIX,ssjj2.com,🎯 全球直连
  - DOMAIN-SUFFIX,starlink.uno,🎯 全球直连
  - DOMAIN-SUFFIX,stkfanli.com,🎯 全球直连
  - DOMAIN-SUFFIX,suyur.com,🎯 全球直连
  - DOMAIN-SUFFIX,sxlljm.com,🎯 全球直连
  - DOMAIN-SUFFIX,tailgdd.com,🎯 全球直连
  - DOMAIN-SUFFIX,tangguobaohe.com,🎯 全球直连
  - DOMAIN-SUFFIX,tclai.top,🎯 全球直连
  - DOMAIN-SUFFIX,tcp.pub,🎯 全球直连
  - DOMAIN-SUFFIX,tcp5.com,🎯 全球直连
  - DOMAIN-SUFFIX,tcy365.net,🎯 全球直连
  - DOMAIN-SUFFIX,thinkerride.com,🎯 全球直连
  - DOMAIN-SUFFIX,tool56.com,🎯 全球直连
  - DOMAIN-SUFFIX,tozi-cn.top,🎯 全球直连
  - DOMAIN-SUFFIX,tumukaoyan.com,🎯 全球直连
  - DOMAIN-SUFFIX,tuxing.art,🎯 全球直连
  - DOMAIN-SUFFIX,u-carloan.com,🎯 全球直连
  - DOMAIN-SUFFIX,ugdocker.link,🎯 全球直连
  - DOMAIN-SUFFIX,ulife.group,🎯 全球直连
  - DOMAIN-SUFFIX,vbkhk.com,🎯 全球直连
  - DOMAIN-SUFFIX,vbkr.com,🎯 全球直连
  - DOMAIN-SUFFIX,vbkrhk.com,🎯 全球直连
  - DOMAIN-SUFFIX,vclbroker.com,🎯 全球直连
  - DOMAIN-SUFFIX,vclbrokers.com,🎯 全球直连
  - DOMAIN-SUFFIX,vcltrade.com,🎯 全球直连
  - DOMAIN-SUFFIX,vgogbuy.com,🎯 全球直连
  - DOMAIN-SUFFIX,warmheart.top,🎯 全球直连
  - DOMAIN-SUFFIX,webs.vc,🎯 全球直连
  - DOMAIN-SUFFIX,wenyi188.com,🎯 全球直连
  - DOMAIN-SUFFIX,wewillpro.com,🎯 全球直连
  - DOMAIN-SUFFIX,wjx.top,🎯 全球直连
  - DOMAIN-SUFFIX,wlcdn88.com,🎯 全球直连
  - DOMAIN-SUFFIX,wwwh.eu.org,🎯 全球直连
  - DOMAIN-SUFFIX,x86pi.com,🎯 全球直连
  - DOMAIN-SUFFIX,xbgjw.com,🎯 全球直连
  - DOMAIN-SUFFIX,xdqtech.com,🎯 全球直连
  - DOMAIN-SUFFIX,xdtool.com,🎯 全球直连
  - DOMAIN-SUFFIX,xiankabao.com,🎯 全球直连
  - DOMAIN-SUFFIX,xiaochuanyun.com,🎯 全球直连
  - DOMAIN-SUFFIX,xinghaiwaimai.com,🎯 全球直连
  - DOMAIN-SUFFIX,xixih.cc,🎯 全球直连
  - DOMAIN-SUFFIX,xn--4kq62z5rby2qupq9ub.top,🎯 全球直连
  - DOMAIN-SUFFIX,xopenbeta.com,🎯 全球直连
  - DOMAIN-SUFFIX,xxrsm.com,🎯 全球直连
  - DOMAIN-SUFFIX,xzsckj.com,🎯 全球直连
  - DOMAIN-SUFFIX,ydayc.com,🎯 全球直连
  - DOMAIN-SUFFIX,yiso.fun,🎯 全球直连
  - DOMAIN-SUFFIX,yongyu.xyz,🎯 全球直连
  - DOMAIN-SUFFIX,yooc.me,🎯 全球直连
  - DOMAIN-SUFFIX,yunzuoye.net,🎯 全球直连
  - DOMAIN-SUFFIX,yzcsoft.com,🎯 全球直连
  - DOMAIN-SUFFIX,z6e.com,🎯 全球直连
  - DOMAIN-SUFFIX,zctnet.top,🎯 全球直连
  - DOMAIN-SUFFIX,zeekrline.com,🎯 全球直连
  - DOMAIN-SUFFIX,zhi10.com,🎯 全球直连
  - DOMAIN-SUFFIX,zhixingyunke.com,🎯 全球直连
  - DOMAIN-SUFFIX,zhongancloud.com,🎯 全球直连
  - DOMAIN-SUFFIX,zjxhedu.com,🎯 全球直连
  - DOMAIN-SUFFIX,znnu.com,🎯 全球直连
  - DOMAIN-SUFFIX,znztv.com,🎯 全球直连
  - DOMAIN-SUFFIX,zuobiao.press,🎯 全球直连
  - IP-CIDR,108.174.48.100/32,🎯 全球直连,no-resolve
  - IP-CIDR,218.78.7.16/32,🎯 全球直连,no-resolve
  - IP-CIDR,5.5.5.5/32,🎯 全球直连,no-resolve
  - IP-CIDR,98.126.27.164/32,🎯 全球直连,no-resolve
  - DOMAIN-SUFFIX,7pzzv.us,🚀 手动选择
  - DOMAIN-SUFFIX,arduino.cc,🚀 手动选择
  - DOMAIN-SUFFIX,clientservices.googleapis.com,🚀 手动选择
  - DOMAIN-SUFFIX,cloudsync-prod.s3.us-east-1.amazonaws.com,🚀 手动选择
  - DOMAIN-SUFFIX,dmhy.org,🚀 手动选择
  - DOMAIN-SUFFIX,googleapis.cn,🚀 手动选择
  - DOMAIN-SUFFIX,hoyolab.com,🚀 手动选择
  - DOMAIN-SUFFIX,ip.sb,🚀 手动选择
  - DOMAIN-SUFFIX,ipify.org,🚀 手动选择
  - DOMAIN-SUFFIX,mtalk.google.com,🚀 手动选择
  - DOMAIN-SUFFIX,onedrive.live.com,🚀 手动选择
  - DOMAIN-SUFFIX,platformio.org,🚀 手动选择
  - DOMAIN-SUFFIX,services.googleapis.cn,🚀 手动选择
  - DOMAIN-SUFFIX,stun.playstation.net,🚀 手动选择
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,🚀 手动选择
  - IP-CIDR,1.0.0.1/32,🚀 手动选择,no-resolve
  - IP-CIDR,1.1.1.1/32,🚀 手动选择,no-resolve
  - GEOSITE,google-cn,🎯 全球直连
  - GEOSITE,category-games@cn,🎯 全球直连
  - DOMAIN-SUFFIX,cm.steampowered.com,🎯 全球直连
  - DOMAIN-SUFFIX,steamcdn-a.akamaihd.net,🎯 全球直连
  - DOMAIN-SUFFIX,steamserver.net,🎯 全球直连
  - IP-CIDR,103.10.124.0/23,🎯 全球直连,no-resolve
  - IP-CIDR,103.28.54.0/24,🎯 全球直连,no-resolve
  - IP-CIDR,146.66.152.0/24,🎯 全球直连,no-resolve
  - IP-CIDR,146.66.155.0/24,🎯 全球直连,no-resolve
  - IP-CIDR,153.254.86.0/24,🎯 全球直连,no-resolve
  - IP-CIDR,155.133.224.0/22,🎯 全球直连,no-resolve
  - IP-CIDR,155.133.230.0/24,🎯 全球直连,no-resolve
  - IP-CIDR,155.133.232.0/23,🎯 全球直连,no-resolve
  - IP-CIDR,155.133.234.0/24,🎯 全球直连,no-resolve
  - IP-CIDR,155.133.236.0/22,🎯 全球直连,no-resolve
  - IP-CIDR,155.133.240.0/23,🎯 全球直连,no-resolve
  - IP-CIDR,155.133.244.0/23,🎯 全球直连,no-resolve
  - IP-CIDR,155.133.246.0/24,🎯 全球直连,no-resolve
  - IP-CIDR,155.133.248.0/21,🎯 全球直连,no-resolve
  - IP-CIDR,162.254.192.0/21,🎯 全球直连,no-resolve
  - IP-CIDR,185.25.182.0/23,🎯 全球直连,no-resolve
  - IP-CIDR,190.217.32.0/22,🎯 全球直连,no-resolve
  - IP-CIDR,192.69.96.0/22,🎯 全球直连,no-resolve
  - IP-CIDR,205.185.194.0/24,🎯 全球直连,no-resolve
  - IP-CIDR,205.196.6.0/24,🎯 全球直连,no-resolve
  - IP-CIDR,208.64.200.0/22,🎯 全球直连,no-resolve
  - IP-CIDR,208.78.164.0/22,🎯 全球直连,no-resolve
  - IP-CIDR,45.121.184.0/24,🎯 全球直连,no-resolve
  - GEOSITE,category-game-platforms-download,🎯 全球直连
  - GEOSITE,category-public-tracker,🎯 全球直连
  - GEOSITE,category-communication,💬 即时通讯
  - GEOSITE,category-social-media-!cn,🌐 社交媒体
  - GEOSITE,openai,🤖 ChatGPT
  - GEOSITE,bing,🤖 Copilot
  - GEOSITE,category-ai-!cn,🤖 AI服务
  - GEOSITE,github,🚀 GitHub
  - GEOSITE,category-speedtest,🚀 测速工具
  - GEOSITE,steam,🎮 Steam
  - GEOSITE,youtube,📹 YouTube
  - GEOSITE,apple-tvplus,🎥 AppleTV+
  - GEOSITE,apple,🍎 苹果服务
  - GEOSITE,microsoft,Ⓜ️ 微软服务
  - GEOSITE,googlefcm,📢 谷歌FCM
  - GEOSITE,google,🇬 谷歌服务
  - GEOSITE,tiktok,🎶 TikTok
  - GEOSITE,netflix,🎥 Netflix
  - GEOSITE,disney,🎥 DisneyPlus
  - GEOSITE,hbo,🎥 HBO
  - GEOSITE,primevideo,🎥 PrimeVideo
  - GEOSITE,category-emby,🎥 Emby
  - GEOSITE,spotify,🎻 Spotify
  - GEOSITE,bahamut,📺 Bahamut
  - GEOSITE,category-games,🎮 游戏平台
  - GEOSITE,category-entertainment,🌎 国外媒体
  - GEOSITE,category-ecommerce,🛒 国外电商
  - GEOSITE,gfw,🚀 手动选择
  - GEOIP,telegram,💬 即时通讯,no-resolve
  - GEOIP,twitter,🌐 社交媒体,no-resolve
  - GEOIP,facebook,🌐 社交媒体,no-resolve
  - GEOIP,google,🇬 谷歌服务,no-resolve
  - GEOIP,netflix,🎥 Netflix,no-resolve
  - GEOSITE,cn,🎯 全球直连
  - GEOIP,cn,🎯 全球直连,no-resolve
  - DST-PORT,1-79,🔀 非标端口
  - DST-PORT,81-442,🔀 非标端口
  - DST-PORT,444-65535,🔀 非标端口
  - MATCH,🐟 漏网之鱼
